[database]
name_bd = "my-test.db"
name_bd_secret = ".streamlit/my-test.db"

[connections]
url = "my-test.db"
url_secret = ".streamlit/my-test.db"
url_login = "data.db"

[connections.my_test_db]
url = "my-test.db"

[connections.sqlite]
dialect = "sqlite"
host = "localhost"
port = "8503"
database = "data.db"
username = "anatolii"
password = "111"
url = 'sqlite:////data/data.db'